// This is the "script" for our playback, generated by the API
export interface SimulationStep {
  step: number;
  currentState: string;
  nextState: string;
  input: string;
  output: string | undefined;
  transitionId: string; // We need this to highlight the transition
}

// This is the event we send to the UI to tell it what to highlight
export interface PlaybackEvent {
  type: "STEP_CHANGE" | "PLAY" | "PAUSE" | "STOP" | "END";
  activeStateId: string | null;
  activeTransitionId: string | null;
  currentStepIndex: number; // -1 (stopped), 0 (step 1), 1 (step 2), etc.
}

export interface PlaybackObserver {
  onPlaybackEvent(event: PlaybackEvent): void;
}

export type PlaybackState = "idle" | "running" | "paused" | "completed";

export class SimulationPlaybackEngine {
  private observers: PlaybackObserver[] = [];
  private steps: SimulationStep[] = [];
  private state: PlaybackState = "idle";
  private speed: number = 1.0; // 1.0 = 1 second per step
  private currentStepIndex: number = -1;
  private timerId: NodeJS.Timeout | null = null;
  private initialStateId: string | null = null;

  constructor() {
    console.log("Playback Engine Initialized");
  }

  subscribe(observer: PlaybackObserver): void {
    this.observers.push(observer);
  }

  private publish(event: PlaybackEvent): void {
    this.observers.forEach((o) => o.onPlaybackEvent(event));
  }

  loadSimulation(steps: SimulationStep[], initialStateId: string): void {
    this.stop();
    this.steps = steps;
    this.initialStateId = initialStateId;
    this.currentStepIndex = -1; // Start before the first step
    this.state = "idle";

    // Set to initial state
    this.publish({
      type: "STOP",
      activeStateId: this.initialStateId,
      activeTransitionId: null,
      currentStepIndex: -1,
    });
  }

  setSpeed(multiplier: number): void {
    // 1x speed = 1s per step. 2x speed = 0.5s per step.
    this.speed = 1.0 / multiplier;
  }

  play(): void {
    if (this.state === "running" || this.steps.length === 0) return;

    this.state = "running";
    this.publish({
      type: "PLAY",
      activeStateId: this.getActiveState(),
      activeTransitionId: this.getActiveTransition(),
      currentStepIndex: this.currentStepIndex,
    });

    // Start the playback loop
    this.executeStep();
  }

  pause(): void {
    if (this.state !== "running") return;
    if (this.timerId) {
      clearTimeout(this.timerId);
      this.timerId = null;
    }
    this.state = "paused";
    this.publish({
      type: "PAUSE",
      activeStateId: this.getActiveState(),
      activeTransitionId: this.getActiveTransition(),
      currentStepIndex: this.currentStepIndex,
    });
  }

  stop(): void {
    if (this.timerId) {
      clearTimeout(this.timerId);
      this.timerId = null;
    }
    this.state = "idle";
    this.currentStepIndex = -1;
    this.publish({
      type: "STOP",
      activeStateId: this.initialStateId,
      activeTransitionId: null,
      currentStepIndex: -1,
    });
  }

  stepForward(): void {
    if (this.state === "running" || this.state === "completed") return;

    this.state = "paused";
    if (this.timerId) {
      clearTimeout(this.timerId);
      this.timerId = null;
    }

    // Check if we are at the end
    if (this.currentStepIndex + 1 >= this.steps.length) {
      this.currentStepIndex = this.steps.length - 1; // Stay on last step
      this.state = "completed";
      this.publish({
        type: "END",
        activeStateId: this.getActiveState(),
        activeTransitionId: null, // No more transitions
        currentStepIndex: this.currentStepIndex,
      });
      return;
    }

    this.currentStepIndex++;
    this.publishStepChange();
  }

  private executeStep(): void {
    if (this.state !== "running") return;

    // Check if we are at the end
    if (this.currentStepIndex + 1 >= this.steps.length) {
      this.currentStepIndex++; // Move to "completed" index (which is steps.length)
      this.publishStepChange(); // Show the final state

      this.state = "completed";
      this.publish({
        type: "END",
        activeStateId: this.getActiveState(),
        activeTransitionId: null,
        currentStepIndex: this.currentStepIndex,
      });
      return;
    }

    this.currentStepIndex++;
    this.publishStepChange();

    // Schedule the next step
    this.timerId = setTimeout(() => {
      this.executeStep();
    }, this.speed * 1000); // speed is in seconds
  }

  private publishStepChange(): void {
    this.publish({
      type: "STEP_CHANGE",
      activeStateId: this.getActiveState(),
      activeTransitionId: this.getActiveTransition(),
      currentStepIndex: this.currentStepIndex,
    });
  }

  // Helper to get the state to highlight for the current step
  private getActiveState(): string | null {
    if (this.currentStepIndex < 0) {
      // Before start
      return this.initialStateId;
    }
    if (this.currentStepIndex >= this.steps.length) {
      // At end
      return this.steps.length > 0
        ? this.steps[this.steps.length - 1].nextState
        : null;
    }
    // Highlight the *destination* state of the current step
    return this.steps[this.currentStepIndex].nextState;
  }

  // Helper to get the transition to highlight for the current step
  private getActiveTransition(): string | null {
    if (
      this.currentStepIndex < 0 ||
      this.currentStepIndex >= this.steps.length
    ) {
      return null;
    }
    return this.steps[this.currentStepIndex].transitionId;
  }
}
